/**
 * KrushiMitra - Rural Farmers' Marketplace Product Catalog
 * Comprehensive catalog covering 6 core agricultural categories with realistic Indian farming data,
 * certified specs, and PM-KUSUM / Govt subsidy markings.
 */

const KRUSHI_PRODUCTS = [
  // ================= 1. SEEDS =================
  {
    id: "seed-101",
    name: "Surya Sharbati Golden Wheat Seeds (HD-3086)",
    hindiName: "सूर्या शरबती उन्नत गेहूं बीज",
    category: "seeds",
    categoryName: "Seeds",
    price: 950,
    originalPrice: 1350,
    rating: 4.9,
    reviewsCount: 428,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80",
    badge: "Bestseller",
    badgeType: "bestseller",
    subsidyEligible: true,
    unit: "40 kg Sack",
    inStock: true,
    stockCount: 18,
    isDeal: true,
    dealEndsIn: 18000,
    description: "High-yielding disease-resistant Sharbati wheat certified by ICAR. Ideal for North & Central Indian plains with exceptional milling and chapati quality.",
    benefits: [
      "Average yield: 22-26 Quintals per acre",
      "Resistant to yellow and brown rust",
      "Low water requirement (3-4 irrigations)",
      "Uniform grain maturity in 125-130 days"
    ],
    usage: "Seed rate: 40 kg/acre. Treat with Trichoderma before sowing for maximum germination."
  },
  {
    id: "seed-102",
    name: "Kaveri Jadoo Hybrid BT Cotton Seeds (BG-II)",
    hindiName: "कावेरी जादू संकर कपास बीज",
    category: "seeds",
    categoryName: "Seeds",
    price: 860,
    originalPrice: 1100,
    rating: 4.8,
    reviewsCount: 312,
    image: "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?auto=format&fit=crop&w=800&q=80",
    badge: "High Yield",
    badgeType: "hot",
    subsidyEligible: false,
    unit: "450 gm Pack",
    inStock: true,
    stockCount: 24,
    isDeal: false,
    description: "Premium Bollgard-II hybrid cotton seeds with superior boll retention, big boll size, and high tolerance to sucking pests.",
    benefits: [
      "Boll weight 5.5 - 6.0 gm",
      "High ginning outturn (36-38%)",
      "Sturdy plant framework prevents lodging",
      "Ideal for rainfed and irrigated black soils"
    ],
    usage: "Spacing: 3x3 ft or 4x1.5 ft depending on soil depth. Sowing depth: 2-3 cm."
  },
  {
    id: "seed-103",
    name: "Pusa Basmati 1718 Paddy Hybrid Seeds",
    hindiName: "पूसा बासमती 1718 धान बीज",
    category: "seeds",
    categoryName: "Seeds",
    price: 1250,
    originalPrice: 1650,
    rating: 4.9,
    reviewsCount: 520,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
    badge: "Govt Certified",
    badgeType: "certified",
    subsidyEligible: true,
    unit: "10 kg Bag",
    inStock: true,
    stockCount: 35,
    isDeal: true,
    dealEndsIn: 14400,
    description: "Bacterial blight resistant improvement of Pusa 1121. Known for ultra-long slender grains (8.5mm+ cooked), captivating aroma, and premium mandi export rates.",
    benefits: [
      "High yield of 24-28 Quintals/acre",
      "Bacterial leaf blight tolerant",
      "Maturity duration: 135-140 days",
      "Superior cooking elongation ratio of 2.5x"
    ],
    usage: "Nursery raising: 5 kg seeds per acre. Transplant 21-25 day old seedlings."
  },
  {
    id: "seed-104",
    name: "KrushiRatan Hybrid Red Onion Seeds (F1 Prema)",
    hindiName: "कृषिरत्न संकर लाल प्याज बीज",
    category: "seeds",
    categoryName: "Seeds",
    price: 780,
    originalPrice: 1050,
    rating: 4.7,
    reviewsCount: 189,
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80",
    badge: "Top Seller",
    badgeType: "hot",
    subsidyEligible: false,
    unit: "500 gm Can",
    inStock: true,
    stockCount: 40,
    isDeal: false,
    description: "Deep dark red, globe-shaped high export quality onions with exceptional storability up to 5-6 months without bolting.",
    benefits: [
      "Average bulb weight 90-120 gm",
      "High pungency and thin neck closure",
      "Excellent resistance to purple blotch",
      "Ready to harvest in 110-120 days after transplanting"
    ],
    usage: "Seed rate: 3-4 kg per acre. Ideal for late Kharif and Rabi sowings."
  },

  // ================= 2. FERTILIZERS =================
  {
    id: "fert-201",
    name: "Bio-NPK Liquid Consortium Micro-Culture",
    hindiName: "बायो-एनपीके तरल कंसोर्टियम जीवाणु खाद",
    category: "fertilizers",
    categoryName: "Fertilizers",
    price: 490,
    originalPrice: 750,
    rating: 4.8,
    reviewsCount: 640,
    image: "https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=800&q=80",
    badge: "Saves 30% Urea",
    badgeType: "certified",
    subsidyEligible: true,
    unit: "1 Litre Bottle",
    inStock: true,
    stockCount: 50,
    isDeal: true,
    dealEndsIn: 21600,
    description: "Certified bio-fertilizer combining Azotobacter (Nitrogen fixing), PSB (Phosphorus solubilizing), and KMB (Potash mobilizing) beneficial bacteria.",
    benefits: [
      "Cuts synthetic chemical fertilizer costs by 25-35%",
      "Enhances natural soil microflora and organic carbon",
      "Mobilizes locked-up soil phosphorus into roots",
      "Eco-safe and 100% biodegradable"
    ],
    usage: "Drip irrigation: 1L per acre with water, or mix 1L in 100kg compost and broadcast."
  },
  {
    id: "fert-202",
    name: "KrushiMitra 100% Pure Organic Vermicompost",
    hindiName: "कृषिमित्र शुद्ध जैविक केंचुआ खाद",
    category: "fertilizers",
    categoryName: "Fertilizers",
    price: 680,
    originalPrice: 950,
    rating: 4.9,
    reviewsCount: 890,
    image: "https://images.unsplash.com/photo-1592417817098-8f3d69102221?auto=format&fit=crop&w=800&q=80",
    badge: "Organic Certified",
    badgeType: "certified",
    subsidyEligible: true,
    unit: "50 kg Moisture-Proof Bag",
    inStock: true,
    stockCount: 65,
    isDeal: false,
    description: "Enriched cow dung vermicompost processed through Australian red wigglers (Eisenia fetida). Rich in humic acid, enzymes, and micro-nutrients.",
    benefits: [
      "Significantly improves soil aeration & water holding",
      "Rich in natural auxins, gibberellins & cytokinin",
      "Safe from weed seeds and pathogen spores",
      "Gradual nutrient release for all crops and orchards"
    ],
    usage: "Field crops: 1-2 tonnes/acre; Fruit orchards: 5-8 kg per tree annually."
  },
  {
    id: "fert-203",
    name: "Chelated Zinc 12% EDTA Micronutrient Spray",
    hindiName: "चिलेटेड जिंक 12% ईडीटीए सूक्ष्म पोषक तत्व",
    category: "fertilizers",
    categoryName: "Fertilizers",
    price: 380,
    originalPrice: 520,
    rating: 4.6,
    reviewsCount: 245,
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=800&q=80",
    badge: "Fast Absorption",
    badgeType: "hot",
    subsidyEligible: false,
    unit: "500 gm Pouch",
    inStock: true,
    stockCount: 30,
    isDeal: false,
    description: "High-grade 100% water-soluble chelated zinc that cures Khaira disease in paddy, leaf curling, and stunted crop growth instantly.",
    benefits: [
      "Direct 100% bio-availability without soil fixation",
      "Enhances chlorophyll synthesis and leaf greening",
      "Compatible with common agricultural spray mixes",
      "Increases tillering and fruit set"
    ],
    usage: "Foliar spray: 1 gm per litre of clean water during early vegetative stage."
  },
  {
    id: "fert-204",
    name: "Neem Coated High Purity Urea Granules (46% N)",
    hindiName: "नीम लेपित यूरिया खाद (46% नाइट्रोजन)",
    category: "fertilizers",
    categoryName: "Fertilizers",
    price: 266,
    originalPrice: 320,
    rating: 4.9,
    reviewsCount: 1420,
    image: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=800&q=80",
    badge: "Govt Subsidized",
    badgeType: "certified",
    subsidyEligible: true,
    unit: "45 kg Bag (DBT Verified)",
    inStock: true,
    stockCount: 120,
    isDeal: false,
    description: "Official Govt subsidized neem-oil coated slow-release urea that prevents nitrogen leaching, volatilization loss, and boosts root uptake.",
    benefits: [
      "Slow-release mechanism prevents burning",
      "Acts as a mild natural soil nematicide",
      "Ensures continuous lush green vegetative growth",
      "Requires 10-15% lower quantity than raw urea"
    ],
    usage: "Apply in split doses according to crop calendar and soil test card report."
  },

  // ================= 3. FARMING TOOLS =================
  {
    id: "tool-301",
    name: "KisanPro 52cc 2-Stroke Multi-Crop Power Weeder",
    hindiName: "किसानप्रो 52cc पावर वीडर / निराई-गुड़ाई मशीन",
    category: "tools",
    categoryName: "Farming Tools",
    price: 11499,
    originalPrice: 16999,
    rating: 4.8,
    reviewsCount: 340,
    image: "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80",
    badge: "32% OFF",
    badgeType: "deal",
    subsidyEligible: true,
    unit: "Complete Kit + 2 Tiller Blades",
    inStock: true,
    stockCount: 9,
    isDeal: true,
    dealEndsIn: 9800,
    description: "Heavy-duty fuel-efficient 52cc mini power cultivator with hardened manganese steel tines. Cleans stubborn weeds between crop rows in sugarcane, cotton, and vegetables 10x faster than manual labor.",
    benefits: [
      "Replaces 8-10 manual farm laborers per day",
      "Tilling width: 25-30 cm, Depth: 4-6 inches",
      "Fuel consumption: Only 650 ml petrol per hour",
      "Easy recoil starter and anti-vibration rubber handles"
    ],
    usage: "Use 2T engine oil mixed in petrol (40ml per litre). Ideal for row crop inter-cultivation."
  },
  {
    id: "tool-302",
    name: "AgroJet 16L 12V-12Ah Dual-Motor Battery Sprayer",
    hindiName: "एग्रोजेट 16L बैटरी चलित कृषि स्प्रेयर पंप",
    category: "tools",
    categoryName: "Farming Tools",
    price: 2499,
    originalPrice: 3800,
    rating: 4.7,
    reviewsCount: 560,
    image: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80",
    badge: "Top Rated",
    badgeType: "bestseller",
    subsidyEligible: false,
    unit: "16 Litre Tank + 4 Nozzles + Charger",
    inStock: true,
    stockCount: 16,
    isDeal: false,
    description: "Powerful double pump backpack knapsack agricultural sprayer with extendable telescopic stainless steel lance and pressure regulator.",
    benefits: [
      "Sprays up to 25-30 tanks on a single 3-hour charge",
      "Twin motor delivers high mist pressure up to 100 PSI",
      "Includes 4 interchangeable misting & jet nozzles",
      "Ergonomic padded back cushion for farmer comfort"
    ],
    usage: "Charge overnight with provided smart auto-cut charger. Clean pump with clear water after chemical sprays."
  },
  {
    id: "tool-303",
    name: "Falcon Forged Steel Heavy Duty Shovel & Kudali Set",
    hindiName: "फॉल्कन मजबूत स्टील फावड़ा एवं कुदाली सेट",
    category: "tools",
    categoryName: "Farming Tools",
    price: 999,
    originalPrice: 1450,
    rating: 4.6,
    reviewsCount: 210,
    image: "https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?auto=format&fit=crop&w=800&q=80",
    badge: "Lifetime Durability",
    badgeType: "certified",
    subsidyEligible: false,
    unit: "2 Piece Combo (Spade + Pickaxe)",
    inStock: true,
    stockCount: 45,
    isDeal: false,
    description: "High-carbon tempered railway steel forged digging tools with rust-resistant epoxy coating and treated ash hardwood grips.",
    benefits: [
      "Precision sharp edges cut through hard rocky soils",
      "Double riveted welded sockets prevent handle snapping",
      "Balanced weight ratio reduces farmer back fatigue",
      "100% Indian blacksmith forged quality"
    ],
    usage: "Ideal for field bund preparation, trench digging, and root aeration."
  },
  {
    id: "tool-304",
    name: "KrushiCraft High Carbon Pruning Shears & Grafting Cutter",
    hindiName: "बागवानी छंटाई कटर एवं ग्राफ्टिंग कैंची",
    category: "tools",
    categoryName: "Farming Tools",
    price: 499,
    originalPrice: 850,
    rating: 4.7,
    reviewsCount: 145,
    image: "https://images.unsplash.com/photo-1598511726623-d2e9996892f0?auto=format&fit=crop&w=800&q=80",
    badge: "41% OFF",
    badgeType: "deal",
    subsidyEligible: false,
    unit: "1 Unit + Spare Spring",
    inStock: true,
    stockCount: 38,
    isDeal: false,
    description: "SK-5 Japanese steel blade bypass secateur designed for clean, crush-free branch pruning in vineyards, pomegranate, mango, and polyhouses.",
    benefits: [
      "Cuts clean branches up to 25mm thickness",
      "Teflon non-stick coating prevents sap buildup",
      "Safety thumb lock mechanism",
      "Ergonomic anti-slip rubberized handles"
    ],
    usage: "Wipe with mustard or mineral oil after pruning to preserve sharpness."
  },

  // ================= 4. IRRIGATION PRODUCTS =================
  {
    id: "irri-401",
    name: "JalDhara Complete 1-Acre Micro Drip Irrigation Kit",
    hindiName: "जलधारा 1 एकड़ सम्पूर्ण ड्रिप सिंचाई किट",
    category: "irrigation",
    categoryName: "Irrigation Products",
    price: 8499,
    originalPrice: 12999,
    rating: 4.9,
    reviewsCount: 380,
    image: "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=800&q=80",
    badge: "Saves 70% Water",
    badgeType: "hot",
    subsidyEligible: true,
    unit: "1 Acre Full System",
    inStock: true,
    stockCount: 12,
    isDeal: true,
    dealEndsIn: 12500,
    description: "ISI-grade complete inline drip irrigation set with 16mm dripline (40cm dripper spacing, 2 LPH), screen filter, venturi fertigation injector, control valves, and joiners.",
    benefits: [
      "Delivers water & nutrients straight to root zones",
      "Eliminates weed growth between crop rows",
      "Increases crop yield by 35-50% with half the water",
      "Qualifies for state micro-irrigation subsidy programs"
    ],
    usage: "Compatible with gravity tanks or 1-5 HP borewell pumps. Operating pressure: 1.0 - 2.5 kg/cm²."
  },
  {
    id: "irri-402",
    name: "Varun Heavy Duty Brass Impact Sprinkler Set (Pack of 4)",
    hindiName: "वरुण पीतल इम्पैक्ट स्प्रिंकलर फव्वारा सेट (4 पीस)",
    category: "irrigation",
    categoryName: "Irrigation Products",
    price: 1899,
    originalPrice: 2799,
    rating: 4.8,
    reviewsCount: 290,
    image: "https://images.unsplash.com/photo-1527842891421-42eec6e703ea?auto=format&fit=crop&w=800&q=80",
    badge: "Wide 40ft Throw",
    badgeType: "bestseller",
    subsidyEligible: false,
    unit: "4 Sprinklers + 3/4\" Riser Couplers",
    inStock: true,
    stockCount: 22,
    isDeal: false,
    description: "Solid forged corrosion-proof brass rotating sprinkler guns for wheat, pulses, groundnut, onion, and fodder crops with adjustable spray arc from 20° to full 360°.",
    benefits: [
      "Covers up to 38-42 feet radius throwing distance",
      "Dual nozzle system provides uniform droplet rain effect",
      "Sand and debris proof internal spring mechanism",
      "Withstands high pump pressure up to 4 bar"
    ],
    usage: "Connect to 3/4 inch female thread risers on HDPE sprinkler pipe lines."
  },
  {
    id: "irri-403",
    name: "KrushiFlex 2.5 Inch UV-Treated Lapeta HDPE Pipe",
    hindiName: "कृषि-फ्लेक्स लपेटा एचडीपीई डिलीवरी पाइप (60 मीटर)",
    category: "irrigation",
    categoryName: "Irrigation Products",
    price: 2150,
    originalPrice: 2900,
    rating: 4.7,
    reviewsCount: 310,
    image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80",
    badge: "Burst-Proof",
    badgeType: "certified",
    subsidyEligible: false,
    unit: "60 Metres Bundle (2.5 Inch)",
    inStock: true,
    stockCount: 28,
    isDeal: false,
    description: "Lightweight flexible woven high-density polyethylene delivery pipe with quick clamp connector. Easy to roll, unroll, and carry across open fields.",
    benefits: [
      "Weighs 75% less than heavy PVC or rubber pipes",
      "Withstands tractor rolling and rough rocky terrain",
      "Multi-layer UV stabilized against intense summer heat",
      "Tested burst pressure: 6.5 kg/cm²"
    ],
    usage: "Unroll flat from pump delivery outlet to field channels. Roll up dry when season ends."
  },
  {
    id: "irri-404",
    name: "SmartKisan Solar Powered Automatic Irrigation Timer Valve",
    hindiName: "स्मार्ट किसान सौर ऊर्जा स्वचालित सिंचाई टाइमर",
    category: "irrigation",
    categoryName: "Irrigation Products",
    price: 3200,
    originalPrice: 4500,
    rating: 4.6,
    reviewsCount: 120,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    badge: "Automation",
    badgeType: "hot",
    subsidyEligible: false,
    unit: "1 Solenoid Valve + Solar Panel + Controller",
    inStock: true,
    stockCount: 15,
    isDeal: false,
    description: "Automate your drip irrigation cycles based on daily hours and interval programs without relying on grid power. Built-in solar charging panel.",
    benefits: [
      "Zero electricity connection needed in remote fields",
      "Prevents crop drowning and saves power bills",
      "Rain sensor delay prevents irrigation on rainy days",
      "Simple rotary dials designed for easy farmer operation"
    ],
    usage: "Mount inline on main irrigation line after filter. Set daily start time and duration."
  },

  // ================= 5. ORGANIC PRODUCTS =================
  {
    id: "org-501",
    name: "NeemShield 10,000 PPM Cold-Pressed Bio-Insecticide",
    hindiName: "नीमशील्ड शुद्ध कोल्ड-प्रेस्ड नीम तेल कीटनाशक",
    category: "organic",
    categoryName: "Organic Products",
    price: 649,
    originalPrice: 950,
    rating: 4.9,
    reviewsCount: 520,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
    badge: "100% Natural",
    badgeType: "certified",
    subsidyEligible: true,
    unit: "1 Litre Bottle (Emulsified)",
    inStock: true,
    stockCount: 42,
    isDeal: true,
    dealEndsIn: 16200,
    description: "High-potency 10,000 PPM Azadirachtin organic repellent that controls whitefly, thrips, aphids, leafminers, and bollworms naturally without killing beneficial honeybees.",
    benefits: [
      "Leaves zero toxic chemical residues on vegetables & fruits",
      "Naturally repels 200+ types of destructive crop pests",
      "Disrupts insect feeding and reproductive life cycles",
      "Pre-emulsified with bio-surfactant: mixes instantly in water"
    ],
    usage: "Dose: 3-4 ml per litre of water. Spray during cool morning or evening hours."
  },
  {
    id: "org-502",
    name: "BioRakshak Trichoderma Viride (2x10^8 CFU/gm)",
    hindiName: "बायोरक्षक ट्राइकोडर्मा विरिडी जैव कवकनाशी",
    category: "organic",
    categoryName: "Organic Products",
    price: 320,
    originalPrice: 480,
    rating: 4.8,
    reviewsCount: 370,
    image: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=800&q=80",
    badge: "Root Protector",
    badgeType: "bestseller",
    subsidyEligible: true,
    unit: "1 kg Foil Pack",
    inStock: true,
    stockCount: 55,
    isDeal: false,
    description: "Antagonistic bio-fungicide that shields crops from devastating soil-borne wilt, root rot, collar rot, damping off, and damping diseases.",
    benefits: [
      "Destroys pathogenic fungi through natural hyperparasitism",
      "Produces enzymes that stimulate aggressive root branching",
      "Safe for organic farming and GAP certified farms",
      "Long shelf life active spore formulation"
    ],
    usage: "Seed treatment: 10 gm/kg seed; Soil application: 2.5 kg mixed with 200 kg vermicompost per acre."
  },
  {
    id: "org-503",
    name: "KrushiAmrit Concentrated Panchagavya Growth Elixir",
    hindiName: "कृषिअमृत संकेंद्रित पंचगव्य जैविक टॉनिक",
    category: "organic",
    categoryName: "Organic Products",
    price: 540,
    originalPrice: 799,
    rating: 4.7,
    reviewsCount: 290,
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80",
    badge: "Vedic Farming",
    badgeType: "certified",
    subsidyEligible: false,
    unit: "2 Litre Jug",
    inStock: true,
    stockCount: 30,
    isDeal: false,
    description: "Traditional fermented Vedic bio-stimulant prepared from pure Desi Gir cow dung, urine, milk, curd, ghee enriched with sugarcane jaggery and tender coconut.",
    benefits: [
      "Dramatic increase in flowering and fruit retention",
      "Boosts natural immunity against pest outbreaks",
      "Enhances taste, fragrance, and gloss of harvest",
      "Restores dead degraded soils with active microbial flora"
    ],
    usage: "Foliar spray: 30 ml per litre water at 15-day intervals during vegetative and flowering phases."
  },
  {
    id: "org-504",
    name: "Prakriti Bio-Phosphate Rich Organic Manure (PROM)",
    hindiName: "प्रकृति समृद्ध जैविक फास्फेट खाद (PROM)",
    category: "organic",
    categoryName: "Organic Products",
    price: 890,
    originalPrice: 1200,
    rating: 4.8,
    reviewsCount: 180,
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=80",
    badge: "DAP Alternative",
    badgeType: "hot",
    subsidyEligible: true,
    unit: "50 kg Bag",
    inStock: true,
    stockCount: 25,
    isDeal: false,
    description: "100% green organic alternative to synthetic DAP fertilizer. Supplies high grade plant-available phosphorus with organic carbon.",
    benefits: [
      "Does not create soil hardness or salinity like chemical DAP",
      "Releases phosphorus steadily throughout crop life",
      "Contains organic carbon (>14%) and beneficial microflora",
      "Approved for export quality residue-free produce"
    ],
    usage: "Basal dressing: 100-150 kg per acre during land preparation before sowing."
  },

  // ================= 6. SOLAR FARMING EQUIPMENT =================
  {
    id: "sol-601",
    name: "SuryaShakti 5HP DC Solar Submersible Water Pump System",
    hindiName: "सूर्यशक्ति 5HP सोलर सबमर्सिबल कृषि पंप सेट",
    category: "solar",
    categoryName: "Solar Farming Equipment",
    price: 64999,
    originalPrice: 135000,
    rating: 5.0,
    reviewsCount: 460,
    image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80",
    badge: "PM-KUSUM 60% Subsidy",
    badgeType: "subsidy",
    subsidyEligible: true,
    unit: "5HP Pump + MPPT Controller + Solar Panels",
    inStock: true,
    stockCount: 6,
    isDeal: true,
    dealEndsIn: 28800,
    description: "MNRE approved ultra-high efficiency solar agricultural borehole pumping kit. Delivers up to 1,80,000 litres of water daily from 350+ ft borewells without electricity bills or diesel costs.",
    benefits: [
      "Eligible for 60% direct state & central PM-KUSUM subsidy",
      "Stainless steel SS-304 anti-rust pump body",
      "Smart MPPT inverter with dry run, lightning & overload safety",
      "25 Years performance warranty on Tier-1 Mono PERC panels"
    ],
    usage: "KrushiMitra certified agro-engineers handle end-to-end installation and subsidy paperwork at your farm."
  },
  {
    id: "sol-602",
    name: "KisanRaksha Solar Electric Fencing Energizer (50 Acres)",
    hindiName: "किसानरक्षा सौर झटका मशीन / सोलर फेंसिंग सिस्टम",
    category: "solar",
    categoryName: "Solar Farming Equipment",
    price: 5499,
    originalPrice: 8900,
    rating: 4.8,
    reviewsCount: 390,
    image: "https://images.unsplash.com/photo-1508873696983-2df5703bc22d?auto=format&fit=crop&w=800&q=80",
    badge: "Wild Animal Safety",
    badgeType: "hot",
    subsidyEligible: false,
    unit: "12V-10KV Energizer + Solar Panel + Battery",
    inStock: true,
    stockCount: 14,
    isDeal: false,
    description: "Safeguard standing crops from wild boars, nilgai, monkeys, and stray cattle. Emits non-lethal, high-voltage deterrent pulses that scare animals away without permanent harm.",
    benefits: [
      "Covers up to 50 acres perimeter fence length",
      "Generates 9.5 - 10 KV pulsed deterrent voltage",
      "Automatic solar charging keeps battery active during cloudy days",
      "Built-in siren alarm sounds if wire is cut or grounded"
    ],
    usage: "Connect red terminal to fence hot wires through insulators, black terminal to deep earthing rod with salt/water."
  },
  {
    id: "sol-603",
    name: "SuryaKeet Automatic Solar Insect & Pest Light Trap",
    hindiName: "सूर्यकीट स्वचालित सोलर कीट पतंग प्रकाश जाल",
    category: "solar",
    categoryName: "Solar Farming Equipment",
    price: 1899,
    originalPrice: 2800,
    rating: 4.7,
    reviewsCount: 280,
    image: "https://images.unsplash.com/photo-1545208942-e1c9c916524b?auto=format&fit=crop&w=800&q=80",
    badge: "Pest Free Farm",
    badgeType: "bestseller",
    subsidyEligible: true,
    unit: "1 Unit with Solar Lamp + Funnel + Stand",
    inStock: true,
    stockCount: 25,
    isDeal: false,
    description: "Eco-friendly solar light trap with specific wave-spectrum UV-violet LED that lures nocturnal crop pests (stem borers, fruit moths, leafhoppers) into a trap chamber.",
    benefits: [
      "Automatically turns ON at dusk and OFF after 4 hours",
      "Captures up to 500-1,000 harmful adult moths every night",
      "Stops pest breeding cycle before eggs are laid on crops",
      "Cuts chemical pesticide spray applications by 50%"
    ],
    usage: "Install 1 trap per acre at crop canopy level. Empty catch tray weekly."
  },
  {
    id: "sol-604",
    name: "KrushiDry 100kg Solar Tunnel Crop & Grain Dehydrator",
    hindiName: "कृषि-ड्राई 100 किग्रा सोलर खाद्य एवं अनाज सुखाने की मशीन",
    category: "solar",
    categoryName: "Solar Farming Equipment",
    price: 18500,
    originalPrice: 26000,
    rating: 4.9,
    reviewsCount: 85,
    image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80",
    badge: "Zero Wastage",
    badgeType: "certified",
    subsidyEligible: true,
    unit: "100 kg Batch Capacity Unit",
    inStock: true,
    stockCount: 5,
    isDeal: false,
    description: "Hygienic solar greenhouse dryer for red chillies, turmeric, ginger, onions, grains, and medicinal herbs. Protects harvest from dust, insects, and rain while drying 3x faster.",
    benefits: [
      "Maintains natural crop colour, aroma, and essential oils",
      "Fetches 25-40% higher price in mandi due to premium grade",
      "Includes solar powered exhaust fans for moisture expulsion",
      "Dries 100 kg chili in just 2 days vs 7 days open sun drying"
    ],
    usage: "Place on flat sunny farm terrace or open ground facing south. Spread harvest evenly on trays."
  }
];

// Export or expose globally for browser
if (typeof window !== "undefined") {
  window.KRUSHI_PRODUCTS = KRUSHI_PRODUCTS;
}
